version: "2"
checks:
  file-lines:
    enabled: true
  method-lines:
    enabled: true
plugins:
  duplication:
    enabled: false
    config:
      languages:
        javascript:
exclude_patterns:
- api/
- auth/
- config/
- helpers/
- models/
- services/
- static/