version: '3'
services:
   backend:
      image: registry.gitlab.com/jdsteam/crowdsource/survey-backend:${VERSION}
      container_name: survey-backend-${VERSION}
      ports: 
         - 3333:3333
      env_file: 
        - .env
      networks:
        - gateway 

networks:
   gateway:
       external:
           name: jds-dev-network
  