version: '3'

  mongodb-primary:
    image: "bitnami/mongodb:4.2"
    user: root
    volumes:
      - ./mongodb-persistence/bitnami:/bitnami
    networks:
      - parse_network
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=123456789
      - MONGODB_ROOT_USERNAME=admin-123
      - MONGODB_ROOT_PASSWORD=password-123
      - MONGODB_USERNAME=admin-123
      - MONGODB_PASSWORD=password-123
      - MONGODB_DATABASE=my_database
    ports:
      - 27017:27017

  mongodb-secondary:
    image: "bitnami/mongodb:4.2"
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_REPLICA_SET_KEY=123456789
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27017
      - MONGODB_PRIMARY_ROOT_USERNAME=admin-123
      - MONGODB_PRIMARY_ROOT_PASSWORD=password-123
    networks:
      - parse_network
    ports:
      - 27027:27017

  mongodb-arbiter:
    image: "bitnami/mongodb:4.2"
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27017
      - MONGODB_PRIMARY_ROOT_PASSWORD=password-123
      - MONGODB_REPLICA_SET_KEY=123456789
    networks:
      - parse_network
    ports:
      - 27037:27017

networks:
  parse_network:
    driver: bridge
    ipam:
      driver: default
volumes:
  mongodb_master_data:
    driver: local


# services:
#   mongo:
#     image: 'bitnami/mongodb:4.4.3'
#     ports:
#       - "27017:27017"
#     environment:
#       - MONGODB_REPLICA_SET_NAME=master
#       - MONGODB_ADVERTISED_HOSTNAME=mongo
#       - MONGODB_REPLICA_SET_MODE=primary
#       #- MONGODB_ROOT_PASSWORD=password123
#       - MONGODB_REPLICA_SET_KEY=replicasetkey123
#     volumes:
#       - 'mongodb_master_data:/bitnami'
#     networks:
#       - crowdsource-api-network

#   mongo-secondary:
#     image: 'bitnami/mongodb:4.4.3'
#     ports:
#        - "27027:27017"
#     depends_on:
#       - mongo
#     environment:
#       - MONGODB_REPLICA_SET_NAME=slave
#       - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
#       - MONGODB_REPLICA_SET_MODE=secondary
#       - MONGODB_INITIAL_PRIMARY_HOST=mongo
#       - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
#       #- MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
#       - MONGODB_REPLICA_SET_KEY=replicasetkey123
#     networks:
#       - crowdsource-api-network

#   mongo-arbiter:
#     image: 'bitnami/mongodb:4.4.3'
#     ports:
#        - "27037:27017"
#     depends_on:
#       - mongo
#     environment:
#       - MONGODB_REPLICA_SET_NAME=arbiter
#       - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
#       - MONGODB_REPLICA_SET_MODE=arbiter
#       - MONGODB_INITIAL_PRIMARY_HOST=mongo
#       - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
#       - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
#       - MONGODB_REPLICA_SET_KEY=replicasetkey123
#     networks:
#       - crowdsource-api-network

#   #backend:
#   #  image: ${I_API}
#   #  build:
#   #      context: .
#   #      dockerfile: Dockerfile
#   #  ports:
#   #      - "3333:3333"
#   #  volumes:
#   #      - .:/app
#   #      - /app/node_modules
#   #  links:
#   #      - mongo
#   #  restart: always
#   #  depends_on:
#   #      - mongo
#   #  environment:
#   #      MONGODB_URI: ${MONGO_DB_URI}
#   #  networks:
#    #     - crowdsource-api-network

# volumes:
#   mongodb_master_data:
#     driver: local

# networks:
#   crowdsource-api-network:
#     driver: bridge
#     ipam:
#       driver: default