version: '3'
services:
   backend:
      build:
         context: .
         dockerfile: Dockerfile.release
      container_name: backend-pikobar-production
      ports: 
         - 3333:3333
      env_file: 
        - .env
      networks:
        - gateway 
      restart: always
      logging:
        driver: "awslogs"
        options:
           awslogs-region: "ap-southeast-1"
           awslogs-group: "pikobar-pelaporan"
           awslogs-stream: "backend-pikobar-production"

networks:
   gateway:
       external:
           name: jds-dev-network
