apiVersion: apps/v1
kind: Deployment
metadata:
  name: pelaporan-api-app
  namespace: pikobar-pelaporan
  labels:
    app: pelaporan-api-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pelaporan-api-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: pelaporan-api-app
    spec:
      automountServiceAccountToken: false
      containers:
        - name: pelaporan-api-app
          image: registry.digitalservice.id/pelaporan-pikobar/api-pelaporan-production:%VERSION%
                
          ports:
            - containerPort: 80
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
          #resources:
          #  requests:
          #    memory: "64Mi"
          #    cpu: "50m"
          #  limits:
          #    memory: "2048Mi"
          #    cpu: "500m"
          envFrom:
          - configMapRef:
              name: pelaporan-configmap-file-prod
          - secretRef:
              name: pelaporan-secret-file-prod
      imagePullSecrets:
        - name: regcred-pelaporan
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/os
                operator: In
                values:
                - linux 
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - jds-rancher-node-01
                - jds-rancher-node-02
                - jds-rancher-node-03
                - jds-rancher-node-04
