apiVersion: v1
kind: Secret
metadata:
  name: pelaporan-secret-file-prod
  namespace: pikobar-pelaporan
data:
  SMS_KEY: "%SMS_KEY%"

  WA_TOKEN: "%WA_TOKEN%"

  FIREBASE_PRIVATE_KEY_ID: "%FIREBASE_PRIVATE_KEY_ID%"
  FIREBASE_PRIVATE_KEY: "%FIREBASE_PRIVATE_KEY%"

  



