version: "2"
checks:
  file-lines:
    enabled: true # default is 250, which is low when we have logic and ui in some files
  method-lines:
    enabled: true # default is 25 which is low for render() methods
plugins:
  duplication:
    enabled: false
    config:
      languages:
        javascript: