# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: API Pikobar Pelaporan Covid-19

on:
  pull_request:
    branches: [ development ]
  push:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

  # coverage:
  #   needs: [ build ]
  #   name: coverage
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@development
  #   - uses: actions/setup-node@development
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #   - run: sudo npm install
  #   - run: sudo npm install --save-dev jest
  #   - uses: paambaati/codeclimate-action@v2.7.5
  #     env:
  #       CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORT_ID }}
  #     with:
  #       coverageCommand: sudo npm run test:coverage